#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
name: soajs-marketplace
version: 1.0.0
appVersion: 1.0.42
description: Helm chart to deploy SOAJS marketplace
