#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
name: soajs-controller
version: 1.0.0
appVersion: 4.2.1
description: Helm chart to deploy SOAJS controller/gateway
