#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
settings:
  image: soajsorg/gateway
  label: dashboard-controller
  version: 1
  catalogId: 5df3ec10fa3912534948f000
  item:
    name: controller
    group: Gateway
  mPort: 5000
  sPort: 4000