#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: soajsprofile
  labels:
    soajs.secret.name: soajsprofile
    soajs.secret.type: Opaque
data:
  soajsprofile: {{ .Files.Get "resources/profile/soajsprofile" | b64enc }}