#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
settings:
  image: soajsorg/console
  label: dashboard-console
  version: 1
  catalogId: 5edf6bf536c77052b0a5e1f1
  item:
    name: console
    group: Console
  mPort: 5009
  sPort: 4009