#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
settings:
  image: soajsorg/urac
  label: dashboard-urac
  version: 3
  catalogId: 5df3ec10fa3912534948f008
  item:
    name: urac
    group: Gateway
  mPort: 5001
  sPort: 4001