#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: fullchain-crt
  labels:
    soajs.secret.name: fullchain-crt
    soajs.secret.type: Opaque
data:
  fullchain-crt: {{ .Files.Get "resources/tls.crt" | b64enc }}