#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: private-key
  labels:
    soajs.secret.name: private-key
    soajs.secret.type: Opaque
data:
  private-key: {{ .Files.Get "resources/tls.key" | b64enc }}