#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.settings.label }}"
  namespace: "{{ .Values.global.namespace }}"
  labels:
    service.image.ts: "{{ .Values.global.TS }}"
    soajs.catalog.id: "{{ .Values.settings.catalogId }}"
    soajs.catalog.v: "1"
    soajs.content: "true"
    soajs.env.code: "dashboard"
    soajs.resource.id: "{{ .Values.settings.resourceId }}"
    soajs.service.group: "{{ .Values.settings.item.group }}"
    soajs.service.label: "{{ .Values.settings.label }}"
    soajs.service.mode: "deployment"
    soajs.service.name: "{{ .Values.settings.item.name }}"
    soajs.service.subtype: "mongo"
    soajs.service.type: "cluster"
    soajs.service.version: "{{ .Values.settings.version }}"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      soajs.service.label: "{{ .Values.settings.label }}"
  template:
    metadata:
      name: "{{ .Values.settings.label }}"
      labels:
        service.image.ts: "{{ .Values.global.TS }}"
        soajs.catalog.id: "{{ .Values.settings.catalogId }}"
        soajs.catalog.v: "1"
        soajs.content: "true"
        soajs.env.code: "dashboard"
        soajs.resource.id: "{{ .Values.settings.resourceId }}"
        soajs.service.group: "{{ .Values.settings.item.group }}"
        soajs.service.label: "{{ .Values.settings.label }}"
        soajs.service.mode: "deployment"
        soajs.service.name: "{{ .Values.settings.item.name }}"
        soajs.service.subtype: "mongo"
        soajs.service.type: "cluster"
        soajs.service.version: "{{ .Values.settings.version }}"
    spec:
      containers:
      - image: "{{ .Values.settings.image }}"
        imagePullPolicy: IfNotPresent
        name: soajsdata-container
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 27017
          name: mongoport
        volumeMounts:
        - mountPath: /data/db
          name: dashboard-soajsdata
        - mountPath: /docker-entrypoint-initdb.d
          name: initscript
        - mountPath: /initial-data
          name: initdata
        readinessProbe:
          exec:
            command:
            - mongo
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: dashboard-soajsdata
        persistentVolumeClaim:
          claimName: soajsdata-volumeclaim
      - name: initscript
        configMap:
          name: soajsdata-initscript-configmap
          defaultMode: 0755
          items:
          - key: load-data.sh
            path: load-data.sh
      - name: initdata
        configMap:
          name: soajs-initialdata-configmap
