#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

apiVersion: v1
name: soajs-oauth
version: 1.0.0
appVersion: 3.1.1
description: Helm chart to deploy SOAJS oauth
