#-------------------------------------------------------------------------------
# @license
# Copyright SOAJS All Rights Reserved.
#
# Use of this source code is governed by an Apache license that can be
# found in the LICENSE file at the root of this repository
#-------------------------------------------------------------------------------

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
settings:
  image: soajsorg/oauth
  label: dashboard-oauth
  version: 1
  catalogId: 5df3ec10fa3912534948f006
  item:
    name: oauth
    group: Gateway
  mPort: 5002
  sPort: 4002